/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FeatureFlags {
  'filtersEnabled' : boolean,
  'musicEnabled' : boolean,
}
export type IssueCategory = { 'other' : null } |
  { 'technical' : null } |
  { 'account' : null } |
  { 'featureRequest' : null };
export type IssueStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface Post {
  'id' : bigint,
  'author' : Principal,
  'timeCreated' : Time,
  'caption' : string,
  'commentsCount' : bigint,
  'image' : [] | [ExternalBlob],
  'likesCount' : bigint,
}
export interface PostInput {
  'author' : Principal,
  'caption' : string,
  'image' : [] | [ExternalBlob],
}
export type ProfileVisibility = { 'privateProfile' : null } |
  { 'publicProfile' : null };
export interface PublicUserProfile {
  'id' : Principal,
  'bio' : string,
  'verified' : VerificationState,
  'username' : string,
  'displayName' : string,
  'blocked' : boolean,
  'followersCount' : bigint,
  'role' : UserRole,
  'email' : [] | [string],
  'hasOrangeTick' : boolean,
  'followingCount' : bigint,
  'visibility' : ProfileVisibility,
  'avatar' : string,
}
export interface StoryInput { 'author' : Principal, 'image' : ExternalBlob }
export interface StoryView {
  'id' : bigint,
  'likeCount' : bigint,
  'isActive' : boolean,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timeCreated' : Time,
  'image' : ExternalBlob,
}
export interface SupportIssue {
  'id' : bigint,
  'status' : IssueStatus,
  'creator' : Principal,
  'description' : string,
  'timeCreated' : Time,
  'category' : IssueCategory,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'officer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationState = { 'blueCheck' : null } |
  { 'orangeTick' : null } |
  { 'unverified' : null } |
  { 'adminOnlyRedCheck' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createPost' : ActorMethod<[PostInput], bigint>,
  'createStory' : ActorMethod<[StoryInput], bigint>,
  'createSupportIssue' : ActorMethod<[IssueCategory, string], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'demoteToUser' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<StoryView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFeatureFlags' : ActorMethod<[], FeatureFlags>,
  'getHomeFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getMySupportIssues' : ActorMethod<[], Array<SupportIssue>>,
  'getPostById' : ActorMethod<[bigint], [] | [Post]>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [PublicUserProfile]>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getStoryById' : ActorMethod<[bigint], [] | [StoryView]>,
  'getSupportIssues' : ActorMethod<[], Array<SupportIssue>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'likeStory' : ActorMethod<[bigint], undefined>,
  'promoteToOfficer' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [
      {
        'bio' : string,
        'username' : string,
        'displayName' : string,
        'email' : [] | [string],
        'visibility' : ProfileVisibility,
        'avatar' : string,
      },
    ],
    undefined
  >,
  'setFeatureFlags' : ActorMethod<[FeatureFlags], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unlikeStory' : ActorMethod<[bigint], undefined>,
  'updateSupportIssueStatus' : ActorMethod<[bigint, IssueStatus], undefined>,
  'updateUserProfileVerification' : ActorMethod<
    [Principal, VerificationState],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];