/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'isActive' : IDL.Bool,
  'author' : IDL.Principal,
  'timeCreated' : Time,
  'image' : ExternalBlob,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'timeCreated' : Time,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'likesCount' : IDL.Nat,
});
export const IssueStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const IssueCategory = IDL.Variant({
  'other' : IDL.Null,
  'technical' : IDL.Null,
  'account' : IDL.Null,
  'featureRequest' : IDL.Null,
});
export const SupportIssue = IDL.Record({
  'id' : IDL.Nat,
  'status' : IssueStatus,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timeCreated' : Time,
  'category' : IssueCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'officer' : IDL.Null,
});
export const ProfileVisibility = IDL.Variant({
  'privateProfile' : IDL.Null,
  'publicProfile' : IDL.Null,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'verified' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'blocked' : IDL.Bool,
  'followersCount' : IDL.Nat,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'followingCount' : IDL.Nat,
  'visibility' : ProfileVisibility,
  'avatar' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timeCreated' : Time,
  'postId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'lastMessageTime' : Time,
});
export const FeatureFlags = IDL.Record({
  'filtersEnabled' : IDL.Bool,
  'musicEnabled' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timeCreated' : Time,
  'conversationId' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'other' : IDL.Null,
  'message' : IDL.Null,
  'supportResponse' : IDL.Null,
  'followRequest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'timeCreated' : Time,
});
export const FollowRequest = IDL.Record({
  'id' : IDL.Nat,
  'requester' : IDL.Principal,
  'denied' : IDL.Bool,
  'timeCreated' : Time,
  'target' : IDL.Principal,
  'approved' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveFollowRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'createStory' : IDL.Func([ExternalBlob], [], []),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'demoteFromOfficer' : IDL.Func([IDL.Principal], [], []),
  'denyFollowRequest' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllSupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getFeatureFlags' : IDL.Func([], [FeatureFlags], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getLikesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOrCreateConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getPendingFollowRequests' : IDL.Func(
      [],
      [IDL.Vec(FollowRequest)],
      ['query'],
    ),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfileById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'promoteToOfficer' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitSupportIssue' : IDL.Func([IssueCategory, IDL.Text], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unverifyUser' : IDL.Func([IDL.Principal], [], []),
  'updateFeatureFlags' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
  'updateSupportIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProfileVisibility],
      [],
      [],
    ),
  'verifyUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'isActive' : IDL.Bool,
    'author' : IDL.Principal,
    'timeCreated' : Time,
    'image' : ExternalBlob,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'timeCreated' : Time,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'likesCount' : IDL.Nat,
  });
  const IssueStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const IssueCategory = IDL.Variant({
    'other' : IDL.Null,
    'technical' : IDL.Null,
    'account' : IDL.Null,
    'featureRequest' : IDL.Null,
  });
  const SupportIssue = IDL.Record({
    'id' : IDL.Nat,
    'status' : IssueStatus,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timeCreated' : Time,
    'category' : IssueCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'officer' : IDL.Null,
  });
  const ProfileVisibility = IDL.Variant({
    'privateProfile' : IDL.Null,
    'publicProfile' : IDL.Null,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'verified' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'blocked' : IDL.Bool,
    'followersCount' : IDL.Nat,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'followingCount' : IDL.Nat,
    'visibility' : ProfileVisibility,
    'avatar' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timeCreated' : Time,
    'postId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'lastMessageTime' : Time,
  });
  const FeatureFlags = IDL.Record({
    'filtersEnabled' : IDL.Bool,
    'musicEnabled' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timeCreated' : Time,
    'conversationId' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'other' : IDL.Null,
    'message' : IDL.Null,
    'supportResponse' : IDL.Null,
    'followRequest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'timeCreated' : Time,
  });
  const FollowRequest = IDL.Record({
    'id' : IDL.Nat,
    'requester' : IDL.Principal,
    'denied' : IDL.Bool,
    'timeCreated' : Time,
    'target' : IDL.Principal,
    'approved' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveFollowRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'createStory' : IDL.Func([ExternalBlob], [], []),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'demoteFromOfficer' : IDL.Func([IDL.Principal], [], []),
    'denyFollowRequest' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllSupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getFeatureFlags' : IDL.Func([], [FeatureFlags], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getLikesByPost' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOrCreateConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getPendingFollowRequests' : IDL.Func(
        [],
        [IDL.Vec(FollowRequest)],
        ['query'],
      ),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfileById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'promoteToOfficer' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitSupportIssue' : IDL.Func([IssueCategory, IDL.Text], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unverifyUser' : IDL.Func([IDL.Principal], [], []),
    'updateFeatureFlags' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
    'updateSupportIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProfileVisibility],
        [],
        [],
      ),
    'verifyUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };