/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'lastMessageTime' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timeCreated' : Time,
  'conversationId' : bigint,
}
export interface Post {
  'id' : bigint,
  'author' : Principal,
  'timeCreated' : Time,
  'caption' : string,
  'commentsCount' : bigint,
  'image' : [] | [ExternalBlob],
  'likesCount' : bigint,
}
export interface PostInput {
  'author' : Principal,
  'caption' : string,
  'image' : [] | [ExternalBlob],
}
export type ProfileVisibility = { 'privateProfile' : null } |
  { 'publicProfile' : null };
export interface PublicUserProfile {
  'id' : Principal,
  'bio' : string,
  'verified' : boolean,
  'username' : string,
  'displayName' : string,
  'blocked' : boolean,
  'followersCount' : bigint,
  'role' : UserRole,
  'email' : [] | [string],
  'hasOrangeTick' : boolean,
  'followingCount' : bigint,
  'visibility' : ProfileVisibility,
  'avatar' : string,
}
export interface StoryInput { 'author' : Principal, 'image' : ExternalBlob }
export interface StoryView {
  'id' : bigint,
  'likeCount' : bigint,
  'isActive' : boolean,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timeCreated' : Time,
  'image' : ExternalBlob,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'officer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createConversation' : ActorMethod<[Principal], bigint>,
  'createPost' : ActorMethod<[PostInput], bigint>,
  'createStory' : ActorMethod<[StoryInput], bigint>,
  'createUserProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'deactivateStory' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getActiveStories' : ActorMethod<[], Array<StoryView>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConversationMessages' : ActorMethod<[bigint], Array<Message>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostCount' : ActorMethod<[], bigint>,
  'getPostsForAuthor' : ActorMethod<[Principal], Array<Post>>,
  'getProfileById' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [PublicUserProfile]>,
  'getStory' : ActorMethod<[bigint], [] | [StoryView]>,
  'getStoryLikes' : ActorMethod<[bigint], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeStory' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PublicUserProfile], undefined>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'setOrangeTick' : ActorMethod<[Principal, boolean], undefined>,
  'setVerifiedStatus' : ActorMethod<[Principal, boolean], undefined>,
  'unlikeStory' : ActorMethod<[bigint], undefined>,
  'updatePost' : ActorMethod<[bigint, PostInput], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string, ProfileVisibility],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];