/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostInput = IDL.Record({
  'author' : IDL.Principal,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const StoryInput = IDL.Record({
  'author' : IDL.Principal,
  'image' : ExternalBlob,
});
export const Time = IDL.Int;
export const StoryView = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timeCreated' : Time,
  'image' : ExternalBlob,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'timeCreated' : Time,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'likesCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'officer' : IDL.Null,
});
export const ProfileVisibility = IDL.Variant({
  'privateProfile' : IDL.Null,
  'publicProfile' : IDL.Null,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'verified' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'blocked' : IDL.Bool,
  'followersCount' : IDL.Nat,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'hasOrangeTick' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'visibility' : ProfileVisibility,
  'avatar' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timeCreated' : Time,
  'conversationId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'lastMessageTime' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
  'createStory' : IDL.Func([StoryInput], [IDL.Nat], []),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deactivateStory' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConversationMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPostsForAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfileById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(StoryView)], ['query']),
  'getStoryLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'setOrangeTick' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setVerifiedStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'unlikeStory' : IDL.Func([IDL.Nat], [], []),
  'updatePost' : IDL.Func([IDL.Nat, PostInput], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProfileVisibility],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostInput = IDL.Record({
    'author' : IDL.Principal,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const StoryInput = IDL.Record({
    'author' : IDL.Principal,
    'image' : ExternalBlob,
  });
  const Time = IDL.Int;
  const StoryView = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timeCreated' : Time,
    'image' : ExternalBlob,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'timeCreated' : Time,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'likesCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'officer' : IDL.Null,
  });
  const ProfileVisibility = IDL.Variant({
    'privateProfile' : IDL.Null,
    'publicProfile' : IDL.Null,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'verified' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'blocked' : IDL.Bool,
    'followersCount' : IDL.Nat,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'hasOrangeTick' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'visibility' : ProfileVisibility,
    'avatar' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timeCreated' : Time,
    'conversationId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'lastMessageTime' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
    'createStory' : IDL.Func([StoryInput], [IDL.Nat], []),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deactivateStory' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConversationMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPostsForAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfileById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(StoryView)], ['query']),
    'getStoryLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'setOrangeTick' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setVerifiedStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'unlikeStory' : IDL.Func([IDL.Nat], [], []),
    'updatePost' : IDL.Func([IDL.Nat, PostInput], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProfileVisibility],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };