/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostInput = IDL.Record({
  'author' : IDL.Principal,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const StoryInput = IDL.Record({
  'author' : IDL.Principal,
  'image' : ExternalBlob,
});
export const IssueCategory = IDL.Variant({
  'other' : IDL.Null,
  'technical' : IDL.Null,
  'account' : IDL.Null,
  'featureRequest' : IDL.Null,
});
export const Time = IDL.Int;
export const StoryView = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timeCreated' : Time,
  'image' : ExternalBlob,
});
export const VerificationState = IDL.Variant({
  'blueCheck' : IDL.Null,
  'orangeTick' : IDL.Null,
  'unverified' : IDL.Null,
  'adminOnlyRedCheck' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'officer' : IDL.Null,
});
export const ProfileVisibility = IDL.Variant({
  'privateProfile' : IDL.Null,
  'publicProfile' : IDL.Null,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'verified' : VerificationState,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'blocked' : IDL.Bool,
  'followersCount' : IDL.Nat,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'hasOrangeTick' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'visibility' : ProfileVisibility,
  'avatar' : IDL.Text,
});
export const FeatureFlags = IDL.Record({
  'filtersEnabled' : IDL.Bool,
  'musicEnabled' : IDL.Bool,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'timeCreated' : Time,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'likesCount' : IDL.Nat,
});
export const IssueStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SupportIssue = IDL.Record({
  'id' : IDL.Nat,
  'status' : IssueStatus,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timeCreated' : Time,
  'category' : IssueCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
  'createStory' : IDL.Func([StoryInput], [IDL.Nat], []),
  'createSupportIssue' : IDL.Func([IssueCategory, IDL.Text], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'demoteToUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFeatureFlags' : IDL.Func([], [FeatureFlags], ['query']),
  'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getMySupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(StoryView)], ['query']),
  'getSupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'likeStory' : IDL.Func([IDL.Nat], [], []),
  'promoteToOfficer' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'bio' : IDL.Text,
          'username' : IDL.Text,
          'displayName' : IDL.Text,
          'email' : IDL.Opt(IDL.Text),
          'visibility' : ProfileVisibility,
          'avatar' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'setFeatureFlags' : IDL.Func([FeatureFlags], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unlikeStory' : IDL.Func([IDL.Nat], [], []),
  'updateSupportIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [], []),
  'updateUserProfileVerification' : IDL.Func(
      [IDL.Principal, VerificationState],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostInput = IDL.Record({
    'author' : IDL.Principal,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const StoryInput = IDL.Record({
    'author' : IDL.Principal,
    'image' : ExternalBlob,
  });
  const IssueCategory = IDL.Variant({
    'other' : IDL.Null,
    'technical' : IDL.Null,
    'account' : IDL.Null,
    'featureRequest' : IDL.Null,
  });
  const Time = IDL.Int;
  const StoryView = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timeCreated' : Time,
    'image' : ExternalBlob,
  });
  const VerificationState = IDL.Variant({
    'blueCheck' : IDL.Null,
    'orangeTick' : IDL.Null,
    'unverified' : IDL.Null,
    'adminOnlyRedCheck' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'officer' : IDL.Null,
  });
  const ProfileVisibility = IDL.Variant({
    'privateProfile' : IDL.Null,
    'publicProfile' : IDL.Null,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'verified' : VerificationState,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'blocked' : IDL.Bool,
    'followersCount' : IDL.Nat,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'hasOrangeTick' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'visibility' : ProfileVisibility,
    'avatar' : IDL.Text,
  });
  const FeatureFlags = IDL.Record({
    'filtersEnabled' : IDL.Bool,
    'musicEnabled' : IDL.Bool,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'timeCreated' : Time,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'likesCount' : IDL.Nat,
  });
  const IssueStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SupportIssue = IDL.Record({
    'id' : IDL.Nat,
    'status' : IssueStatus,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timeCreated' : Time,
    'category' : IssueCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
    'createStory' : IDL.Func([StoryInput], [IDL.Nat], []),
    'createSupportIssue' : IDL.Func([IssueCategory, IDL.Text], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'demoteToUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFeatureFlags' : IDL.Func([], [FeatureFlags], ['query']),
    'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getMySupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getStoryById' : IDL.Func([IDL.Nat], [IDL.Opt(StoryView)], ['query']),
    'getSupportIssues' : IDL.Func([], [IDL.Vec(SupportIssue)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'likeStory' : IDL.Func([IDL.Nat], [], []),
    'promoteToOfficer' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'bio' : IDL.Text,
            'username' : IDL.Text,
            'displayName' : IDL.Text,
            'email' : IDL.Opt(IDL.Text),
            'visibility' : ProfileVisibility,
            'avatar' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'setFeatureFlags' : IDL.Func([FeatureFlags], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unlikeStory' : IDL.Func([IDL.Nat], [], []),
    'updateSupportIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [], []),
    'updateUserProfileVerification' : IDL.Func(
        [IDL.Principal, VerificationState],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };